/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'opencontext-node.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./opencontext-node.android-arm64.node')
          } else {
            nativeBinding = require('@aicontextlab/core-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'opencontext-node.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./opencontext-node.android-arm-eabi.node')
          } else {
            nativeBinding = require('@aicontextlab/core-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'opencontext-node.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./opencontext-node.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@aicontextlab/core-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'opencontext-node.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./opencontext-node.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@aicontextlab/core-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'opencontext-node.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./opencontext-node.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@aicontextlab/core-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'opencontext-node.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./opencontext-node.darwin-universal.node')
      } else {
        nativeBinding = require('@aicontextlab/core-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'opencontext-node.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./opencontext-node.darwin-x64.node')
          } else {
            nativeBinding = require('@aicontextlab/core-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'opencontext-node.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./opencontext-node.darwin-arm64.node')
          } else {
            nativeBinding = require('@aicontextlab/core-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'opencontext-node.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./opencontext-node.freebsd-x64.node')
      } else {
        nativeBinding = require('@aicontextlab/core-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'opencontext-node.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./opencontext-node.linux-x64-musl.node')
            } else {
              nativeBinding = require('@aicontextlab/core-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'opencontext-node.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./opencontext-node.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@aicontextlab/core-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'opencontext-node.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./opencontext-node.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@aicontextlab/core-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'opencontext-node.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./opencontext-node.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@aicontextlab/core-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'opencontext-node.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./opencontext-node.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@aicontextlab/core-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'opencontext-node.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./opencontext-node.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@aicontextlab/core-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'opencontext-node.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./opencontext-node.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@aicontextlab/core-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'opencontext-node.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./opencontext-node.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@aicontextlab/core-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'opencontext-node.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./opencontext-node.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@aicontextlab/core-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { initEnvironment, listFolders, createFolder, renameFolder, moveFolder, removeFolder, listDocs, createDoc, moveDoc, renameDoc, removeDoc, setDocDescription, getDocContent, getDocMeta, getDocByStableId, saveDocContent, reconcileDoc, generateManifest, reconcileFolder, Searcher, Indexer, loadSearchConfig, startIndexSync, isIndexSyncRunning, getIndexSyncStatus } = nativeBinding

module.exports.initEnvironment = initEnvironment
module.exports.listFolders = listFolders
module.exports.createFolder = createFolder
module.exports.renameFolder = renameFolder
module.exports.moveFolder = moveFolder
module.exports.removeFolder = removeFolder
module.exports.listDocs = listDocs
module.exports.createDoc = createDoc
module.exports.moveDoc = moveDoc
module.exports.renameDoc = renameDoc
module.exports.removeDoc = removeDoc
module.exports.setDocDescription = setDocDescription
module.exports.getDocContent = getDocContent
module.exports.getDocMeta = getDocMeta
module.exports.getDocByStableId = getDocByStableId
module.exports.saveDocContent = saveDocContent
module.exports.reconcileDoc = reconcileDoc
module.exports.generateManifest = generateManifest
module.exports.reconcileFolder = reconcileFolder
module.exports.Searcher = Searcher
module.exports.Indexer = Indexer
module.exports.loadSearchConfig = loadSearchConfig
module.exports.startIndexSync = startIndexSync
module.exports.isIndexSyncRunning = isIndexSyncRunning
module.exports.getIndexSyncStatus = getIndexSyncStatus
