/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FolderOptions {
  path: string
  description?: string
}
export interface RenameFolderOptions {
  path: string
  newName: string
}
export interface MoveFolderOptions {
  path: string
  destFolderPath: string
}
export interface RemoveFolderOptions {
  path: string
  force?: boolean
}
export interface ListFolderOptions {
  all?: boolean
}
export interface ListDocsOptions {
  folderPath: string
  recursive?: boolean
}
export interface CreateDocOptions {
  folderPath: string
  name: string
  description?: string
}
export interface MoveDocOptions {
  docPath: string
  destFolderPath: string
}
export interface RenameDocOptions {
  docPath: string
  newName: string
}
export interface RemoveDocOptions {
  docPath: string
}
export interface SetDescriptionOptions {
  docPath: string
  description: string
}
export interface SaveDocOptions {
  docPath: string
  content: string
  description?: string
}
export interface ManifestOptions {
  folderPath: string
  limit?: number
}
export declare function initEnvironment(): NapiResult
export declare function listFolders(options?: ListFolderOptions | undefined | null): NapiResult
export declare function createFolder(options: FolderOptions): NapiResult
export declare function renameFolder(options: RenameFolderOptions): NapiResult
export declare function moveFolder(options: MoveFolderOptions): NapiResult
export declare function removeFolder(options: RemoveFolderOptions): NapiResult
export declare function listDocs(options: ListDocsOptions): NapiResult
export declare function createDoc(options: CreateDocOptions): NapiResult
export declare function moveDoc(options: MoveDocOptions): NapiResult
export declare function renameDoc(options: RenameDocOptions): NapiResult
export declare function removeDoc(options: RemoveDocOptions): NapiResult
export declare function setDocDescription(options: SetDescriptionOptions): NapiResult
export declare function getDocContent(docPath: string): NapiResult
export declare function getDocMeta(docPath: string): NapiResult
export declare function getDocByStableId(stableId: string): NapiResult
export declare function saveDocContent(options: SaveDocOptions): NapiResult
export declare function generateManifest(options: ManifestOptions): NapiResult
/** Search options passed from JavaScript */
export interface SearchOptions {
  query: string
  limit?: number
  mode?: string
  aggregateBy?: string
  docType?: string
}
/** Load search config */
export declare function loadSearchConfig(): any
/**
 * Start the index sync service
 *
 * This service listens to document/folder events and automatically
 * updates the search index in batches at regular intervals.
 *
 * @param interval_secs - Interval in seconds between batch processing (default: 300 = 5 minutes)
 * @returns true if started, false if already running
 */
export declare function startIndexSync(intervalSecs?: number | undefined | null): Promise<boolean>
/** Check if index sync service is running */
export declare function isIndexSyncRunning(): boolean
/**
 * Get pending updates count from index sync service
 * Note: This is approximate as the service runs in background
 */
export declare function getIndexSyncStatus(): any
/** Searcher - async search executor */
export declare class Searcher {
  /**
   * Create a new Searcher instance
   * contexts_root is optional - if not provided, uses default from environment
   */
  static create(): Promise<Searcher>
  /** Execute a search query */
  search(options: SearchOptions): Promise<any>
}
/** Indexer - async index builder */
export declare class Indexer {
  /**
   * Create a new Indexer instance
   * Uses contexts_root from OpenContext environment
   */
  static create(): Promise<Indexer>
  /**
   * Build index for all documents
   * Automatically fetches all documents from OpenContext
   */
  buildAll(): Promise<any>
  /** Index a single file */
  indexFile(relPath: string): Promise<number>
  /** Remove a file from the index */
  removeFile(relPath: string): Promise<void>
  /** Check if index exists */
  indexExists(): Promise<boolean>
  /** Get index statistics */
  getStats(): Promise<any>
  /** Clean/reset the index */
  clean(): Promise<void>
}
